version: '3'
services:
  elmWeb:
    image: "marisn/elmweb:latest"
    container_name: elmWeb
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /root/elmWeb/config.ini:/etc/elmWeb/config.ini
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
